### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by PandoricGalaxy** [0sir1ss/Anubis#4]
![image](https://user-images.githubusercontent.com/86944806/170942368-302f07c3-f364-4a48-87f0-a3eed94f7bbb.png)

**Comment by 0sir1ss** [comment]
I believe this might be related to an issue with the Carbon obfuscator. I'm looking into solutions on how to fix it currently, should be updated soon.

**Comment by 0sir1ss** [comment]
While I am updating the Carbon obfuscator to be more reliable, I have readded the option to use the oxyry obfuscator instead.

**Comment by 0sir1ss** [comment]
I have updated the Carbon obfuscator, problem should be fixed.

**Comment by PandoricGalaxy** [comment]
Thanks! Ill test it out when I'm free

**Comment by PandoricGalaxy** [comment]
@0sir1ss 
![image](https://user-images.githubusercontent.com/86944806/171568811-bc66a745-1685-416a-b9a4-04e9ee11a094.png)
Still the same....

**Comment by PandoricGalaxy** [comment]
@0sir1ss 
when using carbon
![image](https://user-images.githubusercontent.com/86944806/171572243-9f2151c2-fb6f-4cdf-b68e-6c80d0aff83f.png)
and when using Oxyry
![image](https://user-images.githubusercontent.com/86944806/171572361-8f412297-c34a-4e2d-a9bd-270dd3d47038.png)
Im using latest version of Anubis

**Comment by 0sir1ss** [comment]
Hm, my only suggestion is to compare the code to the original and manually fix it yourself.

That looks to be a regex pattern so maybe replace it with r instead of the long variable in front of the "
